version: "3.9"

networks:
  servers_default:
    driver: bridge
    external: true
services:
  database:
    networks:
      - servers_default
    image: mongo:4.4
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=111111
      - MONGO_INITDB_DATABASE=amasona_clone
      - MONGO_INITDB_USERNAME=admin
      - MONGO_INITDB_PASSWORD=123456

    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d
      - data:/data/db

volumes:
  data:
